version: "3.8"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/restaurant
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890
    depends_on:
      - mysqldb
    networks:
      - app-network

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_ROOT_PASSWORD: 1234567890
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: